name: FarmingContest
version: 1.0
main: me.sabin.farmingContest.JacobMain
api-version: 1.18
commands:
  startcontest:
    description: Starts a farming contest
  endcontest:
    description: Ends the current farming contest
  checkscore:
    description: Checks your score in the contest
